from ca import *
from entity.lib import Reference
class Container(Interface):
    def get_element_by_ref(self,ref:Reference) -> object:...
    def search(self,type,**fields) -> list:...
    def register(self,object) -> None:...